# Generated by Django 4.1.7 on 2023-09-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('INSTRUCTOR', 'Instructor')], default='INSTRUCTOR', max_length=13),
        ),
    ]
