# Generated by Django 4.1.7 on 2023-09-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('instructor', 'Instructor')], default='instructor', max_length=13),
        ),
    ]
