# Generated by Django 4.1.7 on 2023-09-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_rol_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'ADMINISTRATOR'), ('instructor', 'INSTRUCTOR')], default='instructor', max_length=15),
        ),
    ]
