# Generated by Django 4.2.4 on 2023-09-01 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation_area', '0001_initial'),
        ('utils', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShawProcess',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.basemodel')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('danger_factor', models.CharField(max_length=255)),
                ('danger_source', models.CharField(max_length=255)),
                ('danger', models.CharField(max_length=255)),
                ('occupational_risk', models.CharField(max_length=255)),
                ('risk_source', models.CharField(max_length=255)),
                ('workers_exposed', models.PositiveSmallIntegerField()),
                ('exposure_time', models.CharField(max_length=255)),
                ('occurrence_probability', models.CharField(max_length=255)),
                ('consequences', models.CharField(max_length=255)),
                ('danger_degree', models.CharField(max_length=255)),
                ('risk_degree', models.CharField(max_length=255)),
                ('danger_description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AT', 'Active'), ('IN', 'Inactive')], default='IN', max_length=2)),
                ('formation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shaw_proccesses', to='formation_area.formationarea')),
                ('formation_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shaw_proccesses', to='formation_area.formationenvironment')),
                ('sub_formation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shaw_proccesses', to='formation_area.subformationarea')),
            ],
            bases=('utils.basemodel',),
        ),
    ]
