# Generated by Django 4.1.7 on 2023-09-13 04:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShawProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='3939af1e-4025-46cb-aa10-1d3b9eaf2df6', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('AT', 'Active'), ('IN', 'Inactive')], default='AT', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('danger_factor', models.CharField(max_length=255)),
                ('danger_source', models.CharField(max_length=255)),
                ('danger', models.CharField(max_length=255)),
                ('occupational_risk', models.CharField(max_length=255)),
                ('risk_source', models.CharField(max_length=255)),
                ('workers_exposed', models.PositiveSmallIntegerField()),
                ('exposure_time', models.CharField(max_length=255)),
                ('occurrence_probability', models.CharField(max_length=255)),
                ('consequences', models.CharField(max_length=255)),
                ('danger_degree', models.CharField(max_length=255)),
                ('risk_degree', models.CharField(max_length=255)),
                ('danger_description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'shaw_process',
                'verbose_name_plural': 'shaw_processes',
                'db_table': 'shaw_process',
            },
        ),
    ]
