# Generated by Django 4.1.7 on 2023-09-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShawProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='52787b2b-6dbe-452f-93c0-3bf694a9f5ef', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('AT', 'Active'), ('IN', 'Inactive')], default='IN', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('danger_factor', models.CharField(max_length=255)),
                ('danger_source', models.CharField(max_length=255)),
                ('danger', models.CharField(max_length=255)),
                ('occupational_risk', models.CharField(max_length=255)),
                ('risk_source', models.CharField(max_length=255)),
                ('workers_exposed', models.PositiveSmallIntegerField()),
                ('exposure_time', models.CharField(max_length=255)),
                ('occurrence_probability', models.CharField(max_length=255)),
                ('consequences', models.CharField(max_length=255)),
                ('danger_degree', models.CharField(max_length=255)),
                ('risk_degree', models.CharField(max_length=255)),
                ('danger_description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'shaw_proccess',
                'verbose_name_plural': 'shaw_proccesses',
                'db_table': 'shaw_proccess',
            },
        ),
    ]
