# Generated by Django 4.1.7 on 2023-09-13 04:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalProccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='3939af1e-4025-46cb-aa10-1d3b9eaf2df6', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('AT', 'Active'), ('IN', 'Inactive')], default='AT', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('activity', models.CharField(max_length=255)),
                ('environmental_aspect', models.CharField(max_length=255)),
                ('impact', models.CharField(max_length=255)),
                ('impact_description', models.CharField(max_length=255)),
                ('recoverability', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
                ('observations', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'environmental_proccess',
                'verbose_name_plural': 'environmental_proccesses',
                'db_table': 'environmental_proccess',
            },
        ),
    ]
