# Generated by Django 4.2.4 on 2023-09-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalProccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='ce3301ce-b11c-4c71-b8ba-369e7bb888fe', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('activity', models.CharField(max_length=255)),
                ('environmental_aspect', models.CharField(max_length=255)),
                ('impact', models.CharField(max_length=255)),
                ('impact_description', models.CharField(max_length=255)),
                ('recoverability', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
                ('observations', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AT', 'Active'), ('IN', 'Inactive')], default='IN', max_length=2)),
                ('formation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_proccesses', to='formation_area.formationarea')),
                ('sub_formation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_proccesses', to='formation_area.subformationarea')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
