# Generated by Django 4.1.7 on 2023-09-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalProccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='52787b2b-6dbe-452f-93c0-3bf694a9f5ef', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('AT', 'Active'), ('IN', 'Inactive')], default='IN', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('activity', models.CharField(max_length=255)),
                ('environmental_aspect', models.CharField(max_length=255)),
                ('impact', models.CharField(max_length=255)),
                ('impact_description', models.CharField(max_length=255)),
                ('recoverability', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
                ('observations', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'environmental_proccess',
                'verbose_name_plural': 'environmental_proccesses',
                'db_table': 'environmental_proccess',
            },
        ),
    ]
