# Generated by Django 4.1.7 on 2023-09-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalproccess',
            name='slug',
            field=models.SlugField(default='3c1312dc-d3ba-4d81-8383-2225c50c38e1', unique=True),
        ),
    ]
