# Generated by Django 4.1.7 on 2023-09-10 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation_area', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('environmental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalproccess',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_proccesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='environmentalproccess',
            name='formation_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_proccesses', to='formation_area.formationarea'),
        ),
        migrations.AddField(
            model_name='environmentalproccess',
            name='formation_environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environmental_proccesses', to='formation_area.formationenvironment'),
        ),
        migrations.AddField(
            model_name='environmentalproccess',
            name='sub_formation_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_proccesses', to='formation_area.subformationarea'),
        ),
    ]
