# Generated by Django 4.2.4 on 2023-09-01 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation_area', '0001_initial'),
        ('environmental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalproccess',
            name='formation_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_proccesses', to='formation_area.formationarea'),
        ),
        migrations.AddField(
            model_name='environmentalproccess',
            name='sub_formation_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_proccesses', to='formation_area.subformationarea'),
        ),
    ]
