# Generated by Django 4.1.7 on 2023-09-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental', '0004_alter_environmentalprocess_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='environmentalprocess',
            name='unique_title_per_formation_environment',
        ),
        migrations.AlterField(
            model_name='environmentalprocess',
            name='slug',
            field=models.SlugField(default='f27d2939-7e94-4706-b6f2-8f2d467066cd', max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='environmentalprocess',
            constraint=models.UniqueConstraint(fields=('formation_area', 'sub_formation_area', 'formation_environment', 'title'), name='unique_env_title_per_formation_environment'),
        ),
    ]
