# Generated by Django 4.2.4 on 2023-09-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='ce3301ce-b11c-4c71-b8ba-369e7bb888fe', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='8c2cc2d9-5b54-4f12-922e-14f374820e67', max_length=25)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('AT', 'Active'), ('IN', 'Inactive')], default='IN', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubFormationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='ce3301ce-b11c-4c71-b8ba-369e7bb888fe', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='f3113176-b3d4-41df-8c3e-9ccdf37444c1', max_length=25)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('AT', 'Active'), ('IN', 'Inactive')], default='IN', max_length=2)),
                ('formation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_formation_areas', to='formation_area.formationarea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormationEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='ce3301ce-b11c-4c71-b8ba-369e7bb888fe', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='f93f5c8d-d6be-449b-b1f8-70b579fd30a6', max_length=25)),
                ('capacity', models.PositiveSmallIntegerField(default=5)),
                ('status', models.CharField(choices=[('AT', 'Active'), ('IN', 'Inactive')], default='IN', max_length=2)),
                ('formation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_environments', to='formation_area.formationarea')),
                ('sub_formation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_environments', to='formation_area.subformationarea')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
