# Generated by Django 4.1.7 on 2023-09-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='52787b2b-6dbe-452f-93c0-3bf694a9f5ef', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('AT', 'Active'), ('IN', 'Inactive')], default='IN', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='4097d7d9-2bb9-43cd-9bc7-2a48aef52b16', max_length=36)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'formation_area',
                'verbose_name_plural': 'formation_areas',
                'db_table': 'formation_area',
            },
        ),
        migrations.CreateModel(
            name='SubFormationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='52787b2b-6dbe-452f-93c0-3bf694a9f5ef', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('AT', 'Active'), ('IN', 'Inactive')], default='IN', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='2564e65a-ef34-44ec-ac09-a60e1b83c09c', max_length=36)),
                ('description', models.CharField(max_length=1000)),
                ('formation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_formation_areas', to='formation_area.formationarea')),
            ],
            options={
                'verbose_name': 'sub_formation_area',
                'verbose_name_plural': 'sub_formation_areas',
                'db_table': 'sub_formation_area',
            },
        ),
        migrations.CreateModel(
            name='FormationEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='52787b2b-6dbe-452f-93c0-3bf694a9f5ef', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('AT', 'Active'), ('IN', 'Inactive')], default='IN', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='52c901a0-2224-4431-99a4-44aaa48d64cb', max_length=36)),
                ('capacity', models.PositiveSmallIntegerField(default=5)),
                ('formation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_environments', to='formation_area.formationarea')),
                ('sub_formation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_environments', to='formation_area.subformationarea')),
            ],
            options={
                'verbose_name': 'formation_environment',
                'verbose_name_plural': 'formation_environments',
                'db_table': 'formation_environment',
            },
        ),
    ]
