# Generated by Django 4.1.7 on 2023-09-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationarea',
            name='name',
            field=models.CharField(default='9ff2c637-1d68-41dc-b6ce-83e3f0584d09', max_length=25),
        ),
        migrations.AlterField(
            model_name='formationarea',
            name='slug',
            field=models.SlugField(default='3c1312dc-d3ba-4d81-8383-2225c50c38e1', unique=True),
        ),
        migrations.AlterField(
            model_name='formationenvironment',
            name='name',
            field=models.CharField(default='567c3d5f-427c-4ce4-93a9-a78672d8fdca', max_length=25),
        ),
        migrations.AlterField(
            model_name='formationenvironment',
            name='slug',
            field=models.SlugField(default='3c1312dc-d3ba-4d81-8383-2225c50c38e1', unique=True),
        ),
        migrations.AlterField(
            model_name='subformationarea',
            name='name',
            field=models.CharField(default='1a791fa9-942e-4ec5-b8d8-5afeb44bd632', max_length=25),
        ),
        migrations.AlterField(
            model_name='subformationarea',
            name='slug',
            field=models.SlugField(default='3c1312dc-d3ba-4d81-8383-2225c50c38e1', unique=True),
        ),
    ]
