# Generated by Django 4.1.7 on 2023-09-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationarea',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='formationarea',
            name='name',
            field=models.CharField(default='2fce168e-89e1-40cc-adfa-ef085c80e7ad', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='formationarea',
            name='slug',
            field=models.SlugField(default='f1b76dae-8793-42bd-9ff3-05ed666ec94b', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='formationenvironment',
            name='name',
            field=models.CharField(default='411f8260-cd6b-4569-8a3e-dde0dd40ff53', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='formationenvironment',
            name='slug',
            field=models.SlugField(default='f1b76dae-8793-42bd-9ff3-05ed666ec94b', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subformationarea',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='subformationarea',
            name='name',
            field=models.CharField(default='3995ecd9-7e8c-4115-a99c-2381fa7ee34f', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='subformationarea',
            name='slug',
            field=models.SlugField(default='f1b76dae-8793-42bd-9ff3-05ed666ec94b', max_length=100, unique=True),
        ),
    ]
