# Generated by Django 4.1.7 on 2023-09-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_area', '0002_alter_formationarea_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationarea',
            name='name',
            field=models.CharField(default='3eef1626-0874-4e45-874a-0f751f87e9f1', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='formationarea',
            name='slug',
            field=models.SlugField(default='5f6948ed-01ea-4a0e-a2da-f20d8cce1fc8', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='formationenvironment',
            name='name',
            field=models.CharField(default='c4307d65-f83b-4c90-a6f5-e625db1c312b', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='formationenvironment',
            name='slug',
            field=models.SlugField(default='5f6948ed-01ea-4a0e-a2da-f20d8cce1fc8', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subformationarea',
            name='name',
            field=models.CharField(default='d25347b8-ba6f-4ba3-a5a1-fd9ba0d384a4', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='subformationarea',
            name='slug',
            field=models.SlugField(default='5f6948ed-01ea-4a0e-a2da-f20d8cce1fc8', max_length=100, unique=True),
        ),
    ]
