# Generated by Django 4.1.7 on 2023-09-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_area', '0003_alter_formationarea_name_alter_formationarea_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationarea',
            name='name',
            field=models.CharField(default='2c1e408e-d09b-4141-b194-1f3fa28ad949', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='formationarea',
            name='slug',
            field=models.SlugField(default='8beb4160-64fa-4065-b731-ef05a150abb5', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='formationenvironment',
            name='name',
            field=models.CharField(default='a77ebdd6-8c51-43ab-a6ca-bcb7811d44ba', max_length=36),
        ),
        migrations.AlterField(
            model_name='formationenvironment',
            name='slug',
            field=models.SlugField(default='8beb4160-64fa-4065-b731-ef05a150abb5', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subformationarea',
            name='name',
            field=models.CharField(default='ff95e435-ced9-4ae7-b38a-e3075fa8ba20', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='subformationarea',
            name='slug',
            field=models.SlugField(default='8beb4160-64fa-4065-b731-ef05a150abb5', max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='formationenvironment',
            constraint=models.UniqueConstraint(fields=('sub_formation_area', 'name'), name='unique_name_per_sub_formation_area'),
        ),
    ]
