# Generated by Django 4.1.7 on 2023-09-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_area', '0004_alter_formationarea_name_alter_formationarea_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationarea',
            name='name',
            field=models.CharField(default='46a14103-ac89-4c5f-98d6-2494c4aa89c1', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='formationarea',
            name='slug',
            field=models.SlugField(default='f27d2939-7e94-4706-b6f2-8f2d467066cd', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='formationenvironment',
            name='name',
            field=models.CharField(default='62765e41-f613-42bd-84c9-47eaf4f7aadd', max_length=36),
        ),
        migrations.AlterField(
            model_name='formationenvironment',
            name='slug',
            field=models.SlugField(default='f27d2939-7e94-4706-b6f2-8f2d467066cd', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subformationarea',
            name='name',
            field=models.CharField(default='4de45425-36d4-4c44-b825-f1845367db50', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='subformationarea',
            name='slug',
            field=models.SlugField(default='f27d2939-7e94-4706-b6f2-8f2d467066cd', max_length=100, unique=True),
        ),
    ]
